apiVersion: v1
kind: Service
metadata:
  name: konga-kong-service
  namespace: kong
spec:
  ports:
  - name: webhook
    port: 80
    protocol: TCP
    targetPort: 1337
  selector:
    app: konga-kong
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: konga-kong
  name: konga-kong
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga-kong
  template:
    metadata:
      labels:
        app: konga-kong
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: arch
                operator: In
                values:
                - arm64
      containers:
      - env:
        - name: TOKEN_SECRET
          value: konga_secret
        - name: NODE_ENV
          value: production
        image: ymedlop/kong:2.0.1-ubuntu
        name: konga
        ports:
        - containerPort: 1337
          name: http
          protocol: TCP